CREATE TABLE HOTELS(
ID_HOTEL NUMBER,
CONSTRAINT HOTEL_PK PRIMARY KEY (ID_HOTEL),
NAME NVARCHAR2(50) NOT NULL,
COUNTRY NVARCHAR2(20) NOT NULL,
CITY NVARCHAR2(20) NOT NULL,
STREET NVARCHAR2(50) NOT NULL)