CREATE TABLE ROOMS(
ID_ROOM NUMBER,
CONSTRAINT ROOM_PK PRIMARY KEY (ID_ROOM),
NUMBER_OF_GUESTS NUMBER NOT NULL,
PRICE NUMBER NOT NULL,
BREAKFAST_INCLUDED NUMBER DEFAULT 1,
PETS_ALLOWED NUMBER DEFAULT 0,
DATE_AVIABLE_FROM DATE NOT NULL,
HOTEL_ID NUMBER,
CONSTRAINT HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS (ID_HOTEL))